### ISSUE TITLE
macOS新系统配置脚本 | RainbowBird's Blog

### ISSUE THREAD

**Issue by luoling8192** [luoling8192/blog#5]
https://blog.luoling.moe/2023/10/27/configure-bash/#more 

 介绍最近在玩黑苹果，因为系统不太稳定，就总需要重装，而且我不太喜欢用时间机器恢复数据。 于是我就写了一个脚本来进行一些重装以后的操作，比如安装需要的软件，改一些系统配置之类。 如果 App Store 有的应用我会默认使用它来安装，其次再使用 Homebrew 安装软件，比如微信之类的（装在容器里更放心）。 你可以自己修改这个脚本来适应你的情况。

**Comment by luoling8192** [comment]
好耶！

**Comment by Clansty** [comment]
好猫
